apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: payments-lambda-s4fl0d
spec:
  sources:
    - name: public-api
      action: allow
  destination:
    name: payments-lambda-s4fl0d