#cloud-config
# Add groups to the system
# Adds the ubuntu group with members 'root' and 'sys'
# and the empty group hashicorp.
groups:
  - ubuntu: [root,sys]
  - hashicorp

# Add users to the system. Users are added after groups are added.
users:
  - default
  - name: terraform
    gecos: terraform
    shell: /bin/bash
    primary_group: hashicorp
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    lock_passwd: false
    ssh_authorized_keys:
      - ssh-rsa AAAAHHHHHH

# Downloads the golang package
packages:
  - golang-go

# Sets the GOPATH & downloads the demo payload
runcmd:
  - sudo apt-get install unzip
  - curl --silent --remote-name https://releases.hashicorp.com/consul/${consul_version}/consul_${consul_version}_linux_amd64.zip
  - unzip consul_${consul_version}_linux_amd64.zip
  - sudo chown root:root consul
  - sudo mv consul /usr/local/bin/
  - consul -autocomplete-install
  - complete -C /usr/local/bin/consul consul
  - sudo useradd --system --home /etc/consul.d --shell /bin/false consul
  - sudo mkdir --parents /opt/consul
  - sudo chown --recursive consul:consul /opt/consul
  - sudo cat << EOF > /etc/systemd/system/consul.service
  - [Unit]
  - Description="HashiCorp Consul - A service mesh solution"
  - Documentation=https://www.consul.io/
  - Requires=network-online.target
  - After=network-online.target
  - ConditionFileNotEmpty=/etc/consul.d/server.hcl
  - [Service]
  - User=consul
  - Group=consul
  - ExecStart=/usr/local/bin/consul agent -config-dir=/etc/consul.d/
  - ExecReload=/usr/local/bin/consul reload
  - KillMode=process
  - Restart=always
  - LimitNOFILE=65536
  - [Install]
  - WantedBy=multi-user.target
  - EOF
  - sudo mkdir --parents /etc/consul.d
  - sudo touch /etc/consul.d/server.hcl
  - sudo chown --recursive consul:consul /etc/consul.d
  - sudo chmod 640 /etc/consul.d/server.hcl
  - cat << EOF > /etc/consul.d/server.hcl
  - node_name = "consul-server"
  - server = true
  - datacenter = "dc1"
  - data_dir = "/opt/consul"
  - bootstrap = true
  - ui_config {
  -     enabled = true
  - }
  - addresses {
  -     http = "0.0.0.0"
  - }
  - acl { 
  - 	enable = true
  - 	default_policy = "deny"
  - 	enable_token_persistence = true
  - 	tokens {
  - 		master = "${consul_acl_token}"
  - 		agent = ${consul_acl_token}
  - 	}
  - }
  - connect {
  -     enabled = true
  - }
  - verify_incoming = false
  - verify_outgoing = false
  - verify_server_hostname = false
  - encrypt = "${consul_gossip_key}"
  - ca_file = "${consul_ca_cert}"
  - EOF
  - sudo systemctl enable consul
  - sudo service consul start
  - sudo service consul status  