global:
  name: consul
  enabled: false
#  datacenter: dc1
#  image: hashicorp/consul-enterprise:1.11.4-ent
  enableConsulNamespaces: true
  enterpriseLicense:
    secretName: consul-ent-license
    secretKey: key
  acls:
    manageSystemACLs: true
    bootstrapToken:
      secretName: consul-bootstrap-token
      secretKey: token
  gossipEncryption:
    secretName: consul-gossip-key
    secretKey: key
  tls:
    enabled: true
    enableAutoEncrypt: true
    caCert:
      secretName: consul-ca-cert
      secretKey: tls.crt
externalServers:
  enabled: true
#  hosts:
#  - ${HCP_CONSUL_PUBLIC_ENDPOINT}
  httpsPort: 443
  useSystemRoots: true
#  k8sAuthMethodHost: ${KUBERNETES_CONTROL_PLANE}
client:
  enabled: true
  grpc: true
#  join:
#  - ${HCP_CONSUL_ADDR}
connectInject:
  enabled: true
  envoyExtraArgs: "--component-log-level upstream:debug,http:debug,router:debug,config:debug"
  aclBindingRuleSelector: ''
  consulNamespaces:
    mirroringK8S: true
  transparentProxy:
    defaultEnabled: false
controller:
  enabled: true

